services:
  - type: web
    name: stock-prediction-studio
    plan: free
    runtime: python
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.13
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn stock_prediction_app.app:app

